title: Hanif Noer Rofiq
description: AI engineer and computer vision researcher studying diffusion-based image generation and watermarking at Monash University.
url: https://hanifnoerr.github.io
lang: en-AU
timezone: Australia/Melbourne
google_analytics: "G-4WER3BZ74H"
exclude:
  - Gemfile
  - jekyll-theme-minimal.gemspec
  - script
  - docs
