title: Hanif Noer Rofiq's CV
logo: /assets/img/logo.png
description: My goal with this website is to give you a sense of who I am and what I can do, as well as provide an easy way to get in touch with me. Thanks for stopping by, and I look forward to hearing from you!
show_downloads: false
google_analytics: "G-4WER3BZ74H"
theme: jekyll-theme-minimal
