title: Hanif Noer Rofiq
logo: /assets/img/tes.jpg
description: I am a data analyst currently working at the Ministry of Finance. With a strong background in analytics, finance, and management, I have been able to analyze and interpret complex financial data to help inform strategic decision-making. Through my work, I have been able to provide valuable insights and recommendations that have contributed to the success of numerous projects and initiatives. Thank you for visiting my portfolio, and I look forward to connecting with you!
show_downloads: false
google_analytics: "G-4WER3BZ74H"
theme: jekyll-theme-minimal
