title: Hanif Noer Rofiq
logo: /assets/tes.png
description: I am a data analyst with a strong background in analytics, finance, and management. Through my work, I have been able to provide valuable insights and recommendations that have contributed to the success of numerous projects and initiatives. 
show_downloads: false
google_analytics: "G-4WER3BZ74H"
theme: jekyll-theme-minimal
